
[z Fs]=audioread('D:\StudiesRelated\Projects\SPC\Training_GridsAtoC\Grid_A\Audio_recordings\Train_Grid_A_A2.wav');
t=1000*100;
no=t/2;
w=rectwin(t);
figure;
subplot(3,2,1);
spectrogram(z,w,no,t,Fs);
[z Fs]=audioread('D:\StudiesRelated\Projects\SPC\Training_GridsAtoC\Grid_A\Power_recordings\Train_Grid_A_P1.wav');
t=1000*100;
w=gausswin(t);
subplot(3,2,2);
spectrogram(z,w,no,t,Fs);
[z Fs]=audioread('D:\StudiesRelated\Projects\SPC\Training_GridsAtoC\Grid_B\Audio_recordings\Train_Grid_B_A2.wav');
t=1000*100;
w=gausswin(t);
subplot(3,2,3);
spectrogram(z,w,no,t,Fs);
[z Fs]=audioread('D:\StudiesRelated\Projects\SPC\Training_GridsAtoC\Grid_B\Power_recordings\Train_Grid_B_P1.wav');
t=1000*100;
w=gausswin(t);
subplot(3,2,4);
spectrogram(z,w,no,t,Fs);
[z Fs]=audioread('D:\StudiesRelated\Projects\SPC\Training_GridsAtoC\Grid_C\Audio_recordings\Train_Grid_C_A2.wav');
t=1000*100;
w=gausswin(t);
subplot(3,2,5);
spectrogram(z,w,no,t,Fs);
[z Fs]=audioread('D:\StudiesRelated\Projects\SPC\Training_GridsAtoC\Grid_C\Power_recordings\Train_Grid_C_P1.wav');
t=1000*100;
w=gausswin(t);
subplot(3,2,6);
spectrogram(z,w,no,t,Fs);